package comp3110.crossingDomain;

/**
 *
 * Defines the interface that Crossing Hardware domains use to communicate with the Crossing
 * domain. It represents assumptions that the Crossing domain makes about the events that are
 * generated by a crossing hardware domain.
 *
 * This interface is part of the specification of an Explicit Bridge between the Crossing Domain and
 * some other domain that provides access to the crossing hardware.
 */

 
// This is the client side of the explicit bridge between the Crossing and
// the Crossing hardware domains. This interface declares those methods by which the hardware
// domain can communicate with the Crossing domain
// 
public interface CrossingToHardwareClientInterface {

 /**
  * Used by a crossing hardware domain to tell the Crossing domain that a crossingRequest
  * event has occurred in the real world. 
  *
  */
  public void processCrossingRequestEvent();
  
 /**
  * Used by a crossing hardware domain to tell the Crossing domain that a setFailMode
  * event has occurred in the real world. 
  */
  public void processSetFailModeEvent();
  
 /**
  * Used by a crossing hardware domain to tell the Crossing domain that a setTrafficMode
  * event has occurred in the real world. 
  */
  public void processSetTrafficModeEvent();
  

}
